name: admin-ui-incall
namespace: official
version: 1.2.0-2
author: Wazo Team
display_name: Incalls
min_wazo_version: 18.02
tags:
  - routing
homepage: https://github.com/wazo-pbx/wazo-admin-ui-incall
depends:
  - name: admin-ui-context
    namespace: official
  - name: admin-ui-extension
    namespace: official
