plugin_format_version: 2
name: admin-ui-incall
namespace: official
version: 1.1.0-4
author: Wazo Team
display_name: Incalls
min_wazo_version: 18.01
tags:
  - routing
homepage: https://github.com/wazo-pbx/wazo-admin-ui-incall
depends:
  - name: admin-ui-context
    namespace: official
    version: ">= 1.1.1-2"
  - name: admin-ui-extension
    namespace: official
    version: ">= 1.2.0-2"
